-- ShopAssist :: SQLite schema
-- Target: SQLite 3.35+ (Python's built-in sqlite3 module)
-- Purpose: zero-infrastructure local development database.
--
-- Table and column names deliberately match shopassist's application-level
-- schema (customer_id / item_id / session_id / order_id, not a generic
-- "id") so services/ecommerce_client.py's SQL runs unchanged against this
-- database - see ../../docs/database-design.md.
--
-- customer_id / item_id / order_id are human-readable business keys
-- (cust-1001, item-1001, ord-1001 - see seeds/seed.sql) rather than
-- autoincrementing integers, same idea as session_id already being a
-- recognizable token - so they're supplied explicitly on INSERT.
--
-- Adaptations vs postgres/schema/*.sql (the source of truth for column
-- shape, since SQLite has no independent constraints/indexes lifecycle to
-- protect - everything is inlined into this one file):
--   - ENUM types          -> TEXT + CHECK constraint
--   - UUID / gen_random_uuid() -> TEXT (uuid4 hex generated by seed data / the app)
--   - INET                -> TEXT
--   - TIMESTAMPTZ         -> TEXT (ISO-8601), DEFAULT CURRENT_TIMESTAMP
--   - line_total generated column -> plain column, computed on insert
--     (SQLite generated-column support varies by build; kept explicit for
--     portability)
--
-- This file is idempotent: it can be re-run against an existing database
-- file without error (CREATE TABLE/INDEX IF NOT EXISTS).

PRAGMA foreign_keys = ON;

-- ---------------------------------------------------------------------------
-- customers
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS customers (
    customer_id     TEXT PRIMARY KEY,
    first_name      VARCHAR(100)  NOT NULL,
    last_name       VARCHAR(100)  NOT NULL,
    email           VARCHAR(255)  NOT NULL UNIQUE,
    phone           VARCHAR(20),
    address_line1   VARCHAR(255),
    address_line2   VARCHAR(255),
    city            VARCHAR(100),
    state           VARCHAR(100),
    postal_code     VARCHAR(20),
    country         VARCHAR(100)  DEFAULT 'India',
    is_active       BOOLEAN       NOT NULL DEFAULT 1,
    created_at      TEXT          NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TEXT          NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ---------------------------------------------------------------------------
-- items
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS items (
    item_id         TEXT PRIMARY KEY,
    name            VARCHAR(255)  NOT NULL,
    description     TEXT,
    category        VARCHAR(100),
    price           NUMERIC(10,2) NOT NULL CHECK (price >= 0),
    mrp             NUMERIC(10,2) CHECK (mrp >= price),
    stock_quantity  INTEGER       NOT NULL DEFAULT 0,
    is_active       BOOLEAN       NOT NULL DEFAULT 1,
    created_at      TEXT          NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TEXT          NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ---------------------------------------------------------------------------
-- sessions
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS sessions (
    session_id      TEXT PRIMARY KEY,
    customer_id     TEXT          REFERENCES customers(customer_id) ON DELETE SET NULL,
    ip_address      TEXT,
    user_agent      TEXT,
    device_type     VARCHAR(50),
    status          TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'expired', 'terminated')),
    started_at      TEXT          NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_seen_at    TEXT          NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ended_at        TEXT,
    CHECK (ended_at IS NULL OR ended_at >= started_at)
);

-- ---------------------------------------------------------------------------
-- orders
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS orders (
    order_id        TEXT PRIMARY KEY,
    customer_id     TEXT          NOT NULL REFERENCES customers(customer_id) ON DELETE RESTRICT,
    session_id      TEXT          REFERENCES sessions(session_id) ON DELETE SET NULL,
    status          TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'confirmed', 'shipped', 'delivered', 'cancelled', 'returned')),
    subtotal        NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (subtotal >= 0),
    discount        NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (discount >= 0),
    shipping_fee    NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (shipping_fee >= 0),
    total_amount    NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (total_amount >= 0),
    shipping_address TEXT,
    placed_at       TEXT          NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TEXT          NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ---------------------------------------------------------------------------
-- order_items
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS order_items (
    order_id        TEXT          NOT NULL REFERENCES orders(order_id) ON DELETE CASCADE,
    item_id         TEXT          NOT NULL REFERENCES items(item_id)  ON DELETE RESTRICT,
    quantity        INTEGER       NOT NULL CHECK (quantity > 0),
    unit_price      NUMERIC(10,2) NOT NULL CHECK (unit_price >= 0),
    line_total      NUMERIC(12,2) NOT NULL CHECK (line_total >= 0),
    PRIMARY KEY (order_id, item_id)
);

-- ---------------------------------------------------------------------------
-- Indexes
-- ---------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_items_category         ON items(category);
CREATE INDEX IF NOT EXISTS idx_sessions_customer_id    ON sessions(customer_id);
CREATE INDEX IF NOT EXISTS idx_orders_customer_id      ON orders(customer_id);
CREATE INDEX IF NOT EXISTS idx_orders_status           ON orders(status);
CREATE INDEX IF NOT EXISTS idx_order_items_order_id    ON order_items(order_id);
CREATE INDEX IF NOT EXISTS idx_order_items_item_id     ON order_items(item_id);
